version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-db-assignment
    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret

    ports:
      - "5433:5432"

    volumes:
      - assignment_postgres_data:/var/lib/postgresql/data

volumes:
  assignment_postgres_data:
